version: '3'
services:
  mongo:
    build: ./mongodb
    volumes:
      - "./mongodb/db:/data/db"
    restart: always
    ports:
      - "27017:27017"
    expose:
      - "27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    networks:
      - db_nw

  flask:
    build: ./flask
    links:
      - mongo
    ports:
      - "5000:5000"
    expose:
      - "5000"
    volumes:
      - ../src:/home/web
    stdin_open: true
    tty: true
    networks:
      - web_nw
      - db_nw

  nginx:
      build: ./nginx
      links:
        - flask
      volumes:
        - "./nginx/log:/var/log/nginx"
        - "../:/usr/share/nginx/html"
      networks:
        - web_nw
      ports:
        - "8080:80"
      expose:
        - "8080" 
      restart: always

networks:
  web_nw:
    driver: bridge
  db_nw:
    driver: bridge

 
