version: '3'
services:
  mongo:
    build: ./mongodb
    volumes:
      - "./mongodb/db:/data/db"
    restart: always
    expose:
      - "27017" 
    ports:
      - "27017:27017"      
    env_file:
      - mongodb/anoia.env
    networks:
      - db_nw

  flask:
    build: ./flask
    depends_on:
      - mongo   
    expose:
      - "5000"    
    volumes:
      - ../src:/home/web
    env_file:
      - flask/anoia.env
    stdin_open: true
    tty: true
    networks:
      - web_nw
      - db_nw

  nginx:
      build: ./nginx      
      volumes:
        - "./nginx/log:/var/log/nginx"
        - "../:/usr/share/nginx/html"
      networks:
        - web_nw
      depends_on:
        - flask
      ports:
        - "8080:80"      
      restart: always

networks:
  web_nw:
    driver: bridge
  db_nw:
    driver: bridge

 
